
import React, { useState, useEffect } from 'react';
import { Bot, Copy, Trash2, Check, Download, ShieldCheck, Zap, Info, Target, Plus, X, Globe } from 'lucide-react';

interface Directive {
  id: string;
  type: 'Allow' | 'Disallow';
  path: string;
}

export const RobotsGenerator: React.FC = () => {
  const [userAgent, setUserAgent] = useState('*');
  const [sitemap, setSitemap] = useState('');
  const [directives, setDirectives] = useState<Directive[]>([
    { id: '1', type: 'Disallow', path: '/admin/' },
    { id: '2', type: 'Allow', path: '/' }
  ]);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const generateRobots = () => {
    let content = `# Robots.txt generated by StrongTools.site\n`;
    content += `User-agent: ${userAgent}\n`;
    
    directives.forEach(d => {
      if (d.path.trim()) {
        content += `${d.type}: ${d.path.trim()}\n`;
      }
    });

    if (sitemap.trim()) {
      content += `\nSitemap: ${sitemap.trim()}\n`;
    }

    setOutput(content);
  };

  useEffect(() => {
    generateRobots();
  }, [userAgent, sitemap, directives]);

  const addDirective = () => {
    setDirectives([...directives, { id: Date.now().toString(), type: 'Disallow', path: '' }]);
  };

  const removeDirective = (id: string) => {
    setDirectives(directives.filter(d => d.id !== id));
  };

  const updateDirective = (id: string, field: keyof Directive, value: string) => {
    setDirectives(directives.map(d => d.id === id ? { ...d, [field]: value } : d));
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'robots.txt';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-20">
      {/* TOOL INTERFACE */}
      <div className="bg-[#0a0a0a] border border-[var(--accent)]/30 rounded-[3rem] p-8 max-w-5xl mx-auto shadow-2xl relative overflow-hidden selection:bg-[var(--accent)] selection:text-black">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-[var(--accent)]/50 to-transparent"></div>
        
        <div className="flex flex-col md:flex-row items-center justify-between gap-6 mb-8">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-[var(--accent)]/10 rounded-2xl border border-[var(--accent)]/20 text-[var(--accent)]">
              <Bot size={28} />
            </div>
            <div>
              <h2 className="text-2xl font-black text-white uppercase italic tracking-tighter">Robots.txt Generator</h2>
              <p className="text-[9px] font-bold text-[var(--accent)]/40 uppercase tracking-[0.4em]">Search Engine Directive Protocol</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          {/* Controls Column */}
          <div className="space-y-6">
            <div className="space-y-3">
              <label className="text-[10px] font-black uppercase tracking-[0.4em] text-gray-500 italic px-2">Global User Agent</label>
              <input 
                type="text"
                value={userAgent}
                onChange={(e) => setUserAgent(e.target.value)}
                className="w-full bg-black border border-white/5 rounded-2xl p-4 text-white font-mono text-sm outline-none focus:border-[var(--accent)]/40 transition-all placeholder-white/5 shadow-inner"
                placeholder="*"
              />
            </div>

            <div className="space-y-3">
              <label className="text-[10px] font-black uppercase tracking-[0.4em] text-gray-500 italic px-2">Path Directives</label>
              <div className="space-y-3 max-h-60 overflow-y-auto custom-scrollbar pr-2">
                {directives.map((d) => (
                  <div key={d.id} className="flex gap-2 animate-in slide-in-from-left-2 duration-300">
                    <select
                      value={d.type}
                      onChange={(e) => updateDirective(d.id, 'type', e.target.value as any)}
                      className="bg-black border border-white/5 rounded-xl px-3 py-3 text-xs font-black uppercase text-[var(--accent)] outline-none"
                    >
                      <option value="Allow">Allow</option>
                      <option value="Disallow">Disallow</option>
                    </select>
                    <input 
                      type="text"
                      value={d.path}
                      onChange={(e) => updateDirective(d.id, 'path', e.target.value)}
                      className="flex-grow bg-black border border-white/5 rounded-xl px-4 py-3 text-white text-xs font-mono outline-none"
                      placeholder="/path/"
                    />
                    <button 
                      onClick={() => removeDirective(d.id)}
                      className="p-3 bg-white/5 text-rose-500 hover:bg-rose-500/10 rounded-xl transition-all"
                    >
                      <X size={14} />
                    </button>
                  </div>
                ))}
              </div>
              <button 
                onClick={addDirective}
                className="w-full py-3 bg-white/5 border border-dashed border-white/10 rounded-xl text-[9px] font-black uppercase tracking-widest text-gray-500 hover:text-[var(--accent)] hover:border-[var(--accent)]/30 transition-all flex items-center justify-center gap-2"
              >
                <Plus size={14} /> Add New Directive
              </button>
            </div>

            <div className="space-y-3 pt-4">
              <label className="text-[10px] font-black uppercase tracking-[0.4em] text-gray-500 italic px-2 flex items-center gap-2">
                <Globe size={12} /> Sitemap URL (Recommended)
              </label>
              <input 
                type="text"
                value={sitemap}
                onChange={(e) => setSitemap(e.target.value)}
                className="w-full bg-black border border-white/5 rounded-2xl p-4 text-emerald-400 font-mono text-sm outline-none focus:border-[var(--accent)]/40 transition-all placeholder-white/5 shadow-inner"
                placeholder="https://example.com/sitemap.xml"
              />
            </div>
          </div>

          {/* Output Preview Column */}
          <div className="space-y-4">
            <div className="flex justify-between items-center px-2">
              <label className="text-[10px] font-black uppercase tracking-[0.4em] text-[var(--accent)] italic">Final Robots.txt Code</label>
              <div className="flex gap-4">
                <button onClick={() => setDirectives([])} className="text-gray-600 hover:text-rose-400 transition-colors"><Trash2 size={14}/></button>
                <button 
                  onClick={handleCopy}
                  className={`flex items-center gap-2 px-3 py-1 rounded-lg transition-all ${copied ? 'text-emerald-400' : 'text-[var(--accent)] hover:text-white opacity-40 hover:opacity-100'}`}
                >
                  {copied ? <Check size={14}/> : <Copy size={14}/>}
                  <span className="text-[9px] font-black uppercase tracking-widest">{copied ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
            </div>
            <div className="relative w-full h-full min-h-[400px] bg-black border border-white/5 rounded-[2.5rem] p-8 text-[var(--accent)] font-mono text-sm leading-relaxed shadow-inner overflow-hidden">
              <pre className="whitespace-pre-wrap">{output}</pre>
              <div className="absolute top-0 right-0 p-12 opacity-[0.03] pointer-events-none rotate-[20deg]">
                <Bot size={200} />
              </div>
            </div>
          </div>
        </div>

        <button
          onClick={downloadFile}
          className="w-full bg-[var(--accent)] text-black py-6 rounded-[2.5rem] font-black text-xl uppercase tracking-tighter italic flex items-center justify-center gap-4 hover:scale-[1.02] active:scale-95 transition-all shadow-[0_20px_50px_rgba(212,175,55,0.3)]"
        >
          <Download size={24}/>
          Download robots.txt
        </button>
      </div>

      {/* ENGLISH DESCRIPTION SECTION */}
      <div className="max-w-4xl mx-auto space-y-24 py-16 px-8 bg-white/[0.01] rounded-[4rem] border border-white/5">
        
        <section className="space-y-6">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-[var(--accent)]/10 flex items-center justify-center text-[var(--accent)]">
              <Info size={24} />
            </div>
            <h3 className="text-3xl font-black text-white font-serif-scholarly italic">What is a Robots.txt File?</h3>
          </div>
          <p className="text-xl text-gray-400 leading-relaxed italic">
            The robots.txt file is a standard used by websites to communicate with web crawlers and other web robots. It informs the agent which areas of the website should not be processed or scanned. This is fundamental for managing crawl budget, preventing the indexing of sensitive admin paths, and ensuring that search engines focus on your most valuable content.
          </p>
        </section>

        <section className="space-y-8">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-[var(--accent)]/10 flex items-center justify-center text-[var(--accent)]">
              <Target size={24} />
            </div>
            <h3 className="text-3xl font-black text-white font-serif-scholarly italic">Strategic Applications</h3>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="p-8 bg-black/40 border border-white/5 rounded-3xl space-y-4 hover:border-[var(--accent)]/30 transition-colors">
              <h4 className="text-[var(--accent)] font-black uppercase tracking-widest text-xs">Crawl Optimization</h4>
              <p className="text-gray-500 text-sm leading-relaxed">Direct search engine bots away from duplicate content or utility scripts to maximize the efficiency of your site's indexing cycle.</p>
            </div>
            <div className="p-8 bg-black/40 border border-white/5 rounded-3xl space-y-4 hover:border-[var(--accent)]/30 transition-colors">
              <h4 className="text-[var(--accent)] font-black uppercase tracking-widest text-xs">Directory Security</h4>
              <p className="text-gray-500 text-sm leading-relaxed">Ensure that private administrative directories or member-only areas are not visible in public search engine results pages (SERPs).</p>
            </div>
            <div className="p-8 bg-black/40 border border-white/5 rounded-3xl space-y-4 hover:border-[var(--accent)]/30 transition-colors">
              <h4 className="text-[var(--accent)] font-black uppercase tracking-widest text-xs">Sitemap Discovery</h4>
              <p className="text-gray-500 text-sm leading-relaxed">Explicitly define the location of your XML sitemap to help bots find and index your latest pages immediately after publishing.</p>
            </div>
          </div>
        </section>

        <section className="space-y-8">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-[var(--accent)]/10 flex items-center justify-center text-[var(--accent)]">
              <Zap size={24} />
            </div>
            <h3 className="text-3xl font-black text-white font-serif-scholarly italic">Key Directives</h3>
          </div>
          <ul className="grid grid-cols-1 md:grid-cols-2 gap-6 text-gray-400 text-lg italic">
            <li className="flex items-start gap-4 p-4 bg-white/5 rounded-2xl">
              <Check className="text-[var(--accent)] shrink-0 mt-1" size={20} />
              <span><strong className="text-white block not-italic">User-agent:</strong> Specifies which crawler the rule applies to (e.g., Googlebot, Bingbot, or * for all).</span>
            </li>
            <li className="flex items-start gap-4 p-4 bg-white/5 rounded-2xl">
              <Check className="text-[var(--accent)] shrink-0 mt-1" size={20} />
              <span><strong className="text-white block not-italic">Disallow:</strong> Prevents the bot from accessing specific files, folders, or path patterns on your server.</span>
            </li>
            <li className="flex items-start gap-4 p-4 bg-white/5 rounded-2xl">
              <Check className="text-[var(--accent)] shrink-0 mt-1" size={20} />
              <span><strong className="text-white block not-italic">Allow:</strong> Overrides a disallow directive for a specific subdirectory, granting permission for bots to enter.</span>
            </li>
            <li className="flex items-start gap-4 p-4 bg-white/5 rounded-2xl">
              <Check className="text-[var(--accent)] shrink-0 mt-1" size={20} />
              <span><strong className="text-white block not-italic">Sitemap:</strong> Points the bot to your comprehensive site map, facilitating a deeper and more accurate crawl.</span>
            </li>
          </ul>
        </section>

      </div>
    </div>
  );
};
